safe:        false
auto:        false
server:      false
server_port: 4000
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins
exclude: ["README.md"]
markdown: rdiscount
pygments: true
paginate: 4
permalink: date